#index:
#    path: /
#    controller: App\Controller\DefaultController::index

products:
  path: /products
  controller: App\Controller\ProductsController::show
  methods: GET

products_add:
  path: /products
  controller: App\Controller\ProductsController::add
  methods: POST

products_del:
  path: /products
  controller: App\Controller\ProductsController::delete
  methods: DELETE
